### ISSUE TITLE
Is neccessary phoneme transcriptions ?

### ISSUE THREAD

**Issue by mohsenhrt** [majidAdibian77/persian_tacotron#1]
Hi thank you because of your codes. I have a question my friend why we use phoneme transcription? And can we train model without phonemes sequence? And finally how to make these phonemes sequences programmatically?

Very Thanks

**Comment by Adibian** [comment]
Hi
We should use phonemes because of Persian language characteristics. In fact many vowels don't appear in a normal Persian text(for example" َ   ُ   ِ" that are necessary in speech). So using phonemes can solve it. Another reason is that this model(like others) works in English characters so the input must be in English.
But I think you can give to it a Persian Text and this model changes any characters to a English character but probably you get a bad result because of two reason that I mentioned.
Creating phonemes from a normal text (grapheme) can be done by sequence-to-sequence models that gets a sequence of words and gives a sequence of phonemes. For Persian language you should search and find a trained model for it or if you have good data train a model for that.

**Comment by mohsenhrt** [comment]
Thank you, intelligent Iranian.

**Comment by Adibian** [comment]
Thanks @mohsenhrt . 
If it was useful don't forget to star this repo :)
